### ISSUE TITLE
技術戦略

### ISSUE THREAD

**Issue by t-kashima** [UNUUU/lumino#1]
## 構成

<img width="396" alt="2016-06-19 23 31 06" src="https://cloud.githubusercontent.com/assets/966751/16177940/ee1c0c3c-3675-11e6-8180-abe4ce2ffce5.png">

IFTTTからメッセージをサーバに送り、サーバからアプリにPush通知で送信する。
アプリはBluetoothを通してluminoにメッセージを送って表示する。

アプリがロック画面などでバックグランドにあってもBluetoothでluminoと通信できる状態にする。
バックグランドにあってもPush通知をフックしてメッセージをBluetoothで送信する。
## アプリ

アプリは1画面で次のことができるようにする。
1. Bluetoothでluminoに接続、キャンセル
2. 定型分のボタンがある
## サーバ
- Herokuを使う

**Comment by t-kashima** [comment]
Bluetoothでメッセージを送信する際は全て自動で送信してしまっていいか？

**Comment by t-kashima** [comment]
どんな形式でluminoに送ればいいのだろうか？色も指定できる？

**Comment by KureoHine** [comment]
8x8ドットマトリクスの部分以外は単色だし、色指定は必要ないです！

**Comment by KureoHine** [comment]
アプリの画面的には接続・解除と定型文のボタン（✔︎Nikeとか\\adidasとか）が出てるといいかな？

**Comment by KureoHine** [comment]
処理は自動で。ふだんiPhoneが介在してる感が無い方が、IoTっぽくてoshare

**Comment by t-kashima** [comment]
> アプリの画面的には接続・解除と定型文のボタン（✔︎Nikeとか\adidasとか）が出てるといいかな？

なるほど、なるほど！！

> 処理は自動で。ふだんiPhoneが介在してる感が無い方が、IoTっぽくてoshare

りょうかいしたー！

**Comment by KureoHine** [comment]
いま試しに組んでるBLEの書式は頭文字1字がコマンドで、以降が内容っていう風にしてる。もっと賢い方法があるんかもわからんけど。

"D123abc"で123abcを表示、とか
"T123456"で現在時刻設定とか

**Comment by t-kashima** [comment]
なるほど、なるほど。
iFTTTからは直接"D123abc"とかを送る感じにすればいいよね！

**Comment by t-kashima** [comment]
`http://lumino.herokuapp.com/ユーザーID/display` にPOSTでmessage=〜を投げると端末にプッシュ通知が飛ぶようにする

**Comment by t-kashima** [comment]
サーバのためのリポジトリを新規で作成した。
https://github.com/unuuu/lumino_api

**Comment by t-kashima** [comment]
IFTTT から iPhoneに表示させたいメッセージがたくさんきた時はどうしようかな。
順番待ちにして随時表示する感じにするかな？
基本処理できるものをさばいて、メッセージのログを作ってそこから好きなものを送信できる？ 
とかでもよさそうかなと思った。他になにかあるかな。

**Comment by KureoHine** [comment]
確かに、複数きた時ね。で言うと順次表示させていく感じかな。恣意的に何かを選択する必要はない気がする。
Arduinoにメッセージを送ると、それに基づいて一連の表示シーケンスを実行して、終わったら待機画面に戻るようなのを想定してたので、待機画面に戻るタイミングでBLEで「終わったよ」っていうのをiPhoneに返してあげればいいんかな？

**Comment by t-kashima** [comment]
> 確かに、複数きた時ね。で言うと順次表示させていく感じかな。恣意的に何かを選択する必要はない気がする。

なるほど！そうだね、終わったよって返してあげればよさそうだけど。
Bluetoothでセントラル、ペリフェラルの関係で双方で通知しあうのって簡単にできるんかな。
双方セントラル、ペリフェラルの状態にすればいいんかな。

自分の理解だとセントラル → ペリフェラルの情報の流れだけかと思ってる。

**Comment by t-kashima** [comment]
あとBluetoothで接続するときにその端末 (lumino) の serviceUUIDとcharacteristicUUIDが必要になりそう。

**Comment by KureoHine** [comment]
このへんとか参考になる？
http://shokai.org/blog/archives/9047

**Comment by t-kashima** [comment]
> ペリフェラル(デバイス)は名前で探して、その中のserviceリストとservice内のcharacteristicsリストから、nRF8001のRX/TXになってる奴をUUIDで識別すればいいだけだった。

接続の時はリストで一覧表示して選ばせるのがよさそうだね！

**Comment by t-kashima** [comment]
構成図通りに実装してBluetoothで接続できたことを確認したのでCloseにする
