### ISSUE TITLE
送信できるメッセージを増やしたい

### ISSUE THREAD

**Issue by t-kashima** [UNUUU/lumino#7]
## 概要
- ボタンを押すことで送信できるメッセージの種類を増やしたい
  - 増やせるような仕組みを考える

**Comment by t-kashima** [comment]
GitHubのmessage.jsonを直接編集してもらうスタイルで対応する予定。
編集されてコミットされると自動ビルドが走ってDeployGateが更新されるように作る。

**Comment by t-kashima** [comment]
一覧で表示されるメッセージの更新方法です。
- 1, <a href="https://github.com/UNUUU/lumino/blob/master/lumino/message.json">messge.json</a>を赤丸の所から編集して「Commit changes」をクリックします。
  - message.jsonはJSON形式でキーが表示される名前、バリューが実際にBLEで書き込まれる値です。{"Adidas": "CDAdidas"}

<img src="https://i.gyazo.com/e35b10d2c1d0f8432bf44d4a85e29f76.png">
- 2, するとビルドが開始されDeployGateに新しいipaがアップロードされるのでそれをダウンロードすれば文言が追加されています。

**Comment by KureoHine** [comment]
なるほど！アプリ上で編集するんかと思ってたけど、この方が手軽っぽい

**Comment by KureoHine** [comment]
それにしても、その度にビルドされるってすごいな。

**Comment by t-kashima** [comment]
一旦そんな感じでまた使用してるうちに定まってきたらデフォルト決めてアプリ上で編集できるようにしようか！

**Comment by t-kashima** [comment]
一旦完了したのでCloseへ
