### ISSUE TITLE
接続時に現在時刻を送信する

### ISSUE THREAD

**Issue by KureoHine** [UNUUU/lumino#8]
送ってあげてほしい。
現状「T」に続いてhour(2)min(2)sec(2)day(2)month(2)year(4)の14桁で入れると設定できる。

**Comment by KureoHine** [comment]
けど、UNIX時間で指定する方がスマートっぽいので、そこはArduino側でUNIX時間が受けれるようにしたい所存。

**Comment by t-kashima** [comment]
そうだね。表示をいろいろかえれてそっちでやったほうがいいかも。
なるほど、じゃあUNIXTimeを接続時に一回送るように作るね！またコマンド決まったら教えて〜！

**Comment by t-kashima** [comment]
「TNOW」で現在時間をUNIX時間で送るコマンドを作ってもいいかもしれないね

**Comment by t-kashima** [comment]
@KureoHine DeployGateの #25 で接続時に現在時刻を「CT + hour(2)min(2)sec(2)day(2)month(2)year(4)」の形式で書き込むようにした！

**Comment by KureoHine** [comment]
時刻きた！
でも頭の"C"はいらない！

**Comment by t-kashima** [comment]
OK！修正する！

**Comment by t-kashima** [comment]
@KureoHine Cを削除しました！DeployGateの#27で確認してみて〜！

**Comment by t-kashima** [comment]
こちら解決したのでCloseにします！
